# Generated by Django 3.0.6 on 2020-05-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(default='null', max_length=10)),
                ('password1', models.CharField(default='null', max_length=20)),
                ('password2', models.CharField(default='null', max_length=20)),
            ],
        ),
    ]
