# Generated by Django 3.0.6 on 2020-05-26 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.IntegerField(default='null', max_length=10),
        ),
        migrations.CreateModel(
            name='supplementsOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onwhey', models.IntegerField(default=0)),
                ('pro', models.IntegerField(default=0)),
                ('mbgold', models.IntegerField(default=0)),
                ('mpwhey', models.IntegerField(default=0)),
                ('rcking', models.IntegerField(default=0)),
                ('mtmass', models.IntegerField(default=0)),
                ('syntha', models.IntegerField(default=0)),
                ('onmass', models.IntegerField(default=0)),
                ('onbcaa', models.IntegerField(default=0)),
                ('mbmulti', models.IntegerField(default=0)),
                ('mpcreatine', models.IntegerField(default=0)),
                ('glutamine', models.IntegerField(default=0)),
                ('asitis', models.IntegerField(default=0)),
                ('onshaker', models.IntegerField(default=0)),
                ('gymeq', models.IntegerField(default=0)),
                ('gymbag', models.IntegerField(default=0)),
                ('totalSum', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
