# Generated by Django 3.0.6 on 2020-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supple', '0003_registration_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(default='null', max_length=200)),
                ('message', models.CharField(default='null', max_length=2000)),
                ('mobileno', models.IntegerField(default='null', max_length=10)),
            ],
        ),
    ]
