# Generated by Django 3.0.6 on 2020-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supple', '0006_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='email',
            field=models.EmailField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='null', max_length=200),
        ),
    ]
