# Generated by Django 3.0.6 on 2020-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supple', '0007_auto_20200527_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('mobilenumber', models.IntegerField(default='null', max_length=10)),
                ('address', models.CharField(default='null', max_length=20)),
            ],
        ),
    ]
